### ISSUE TITLE
国际化

### ISSUE THREAD

**Issue by pyzheng** [repertory/docker-redash#1]
如果我不用docker方式，我只使用你的redash-3.0.0.tar.gz，那么会支持国际化么？谢谢

**Comment by repertory** [comment]
@pyzheng 
redash-3.0.0.tar.gz是redash官方的文件（可以通过md5值进行比对），国内访问不稳定才会提交上来，
而且默认版本是不支持其他语言的

**Comment by pyzheng** [comment]
嗯  首先谢谢你的回复，  我自己试过了   能否赐教如何国际化？  教我个大概方式   谢谢。

**Comment by pyzheng** [comment]
我看到你的dockerfile里面，是复制已经翻译的工程去覆盖才安装。加入我已经安装好了，再翻译html，请教怎么替换。我自己对html翻译，然后直接到/opt/redash/redash/client/app里面做相应的替换，打开界面的时候没有翻译成功，不知道什么原因，你知道么？谢谢
